export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="clean"

HYPHEN_INSENSITIVE="true"
DISABLE_AUTO_UPDATE="true"
ENABLE_CORRECTION="false"
COMPLETION_WAITING_DOTS="true"

HIST_STAMPS="yyyy-mm-dd"

zstyle :omz:plugins:ssh-agent agent-forwarding on
plugins=(git ssh-agent)

export EDITOR=/usr/bin/vim

source $ZSH/oh-my-zsh.sh

if test -S $SSH_AUTH_SOCK; then
    if echo "$SSH_AUTH_SOCK" | grep -Eq '/tmp/ssh-[a-zA-Z0-9]+/agent.[0-9]+'; then
        ln -sf "$SSH_AUTH_SOCK" "/tmp/ssh-agent-$USER-screen"
        export SSH_AUTH_SOCK="/tmp/ssh-agent-$USER-screen"
    fi
fi
